rgb_data_path: /home/dkrivenkov/program/autofocusing/data/data_channel/incoherent_RGBchannels/train_incoherent_RGBChannels
same_data_path: /home/dkrivenkov/program/autofocusing/data/data_channel/incoherent_RGBchannels/testRawData_incoherent_sameProtocol
diff_data_path: /home/dkrivenkov/program/autofocusing/data/data_channel/incoherent_RGBchannels/testRawData_incoherent_diffProtocol
train_ratio: 0.8

train_dataset: 
  _target_: dataset.focusdataset.FocusingDataset
  pattern: Seg(\d+)_defocus(\-?\d+)
  images_data: ???

val_dataset: 
  _target_: dataset.focusdataset.FocusingDataset
  pattern: Seg(\d+)_defocus(\-?\d+)
  images_data: ???

test_dataset: 
  _target_: dataset.focusdataset.FocusingDataset
  pattern: defocus(\-?\d+)
  images_data: ???

train_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  drop_last: true
  num_workers: 10

val_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  num_workers: 10

test_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 4
  num_workers: 10


train_transform:
  _target_: dataset.transform.TrainFocusingTransform
  mean: 
    - 140.87
    - 117.73
    - 131.95
  std:
    - 17.15
    - 20.52
    - 20.51
  add_fourier: false

val_transform:
  _target_: dataset.transform.ValFocusingTransform
  mean: 
    - 140.87
    - 117.73
    - 131.95
  std:
    - 17.15
    - 20.52
    - 20.51
  add_fourier: false

test_transform:
  _target_: dataset.transform.TestFocusingTransform
  mean: 
    - 140.87
    - 117.73
    - 131.95
  std:
    - 17.15
    - 20.52
    - 20.51
  add_fourier: false
  crop_size:
    - 2016
    - 2240
